language: python
sudo: required
dist: trusty
python: '3.4'

# before_install:

cache:
    - pip
install:
    - pip install -r requirements.txt
    - pip install -r test_requirements.txt

script:
    - python tests/test_app.py

# after_success:

branches:
    only:
        - master
