language: python
sudo: required
dist: trusty
python: '3.4'

# before_install:

cache:
    - pip
install:
    - pip install -r requirements.txt
    - pip install -r requirements-test.txt
    - pip install codecov
    - pip install coverage

script:
    - export RAS_SM_PATH=./
    - export NOTIFY_VIA_LOGGING=1
    - coverage run run_tests.py

after_success:
    - codecov

branches:
    only:
        - master
