language: python
sudo: required
dist: trusty
python: '3.4'

# before_install:

cache:
    - pip
install:
    - pip install -r requirements.txt
    - pip install -r test_requirements.txt
    - pip install codecov
    - pip install coverage

script:
    - coverage run run_tests.py
    - coverage report

after_success:
    - codecov

branches:
    only:
        - master
