language: python
sudo: required
dist: trusty
python: '3.4'

# before_install:

cache:
    - pip

install:
    - pip install -r requirements.txt
    - pip install -r requirements-test.txt
    - pip install codecov
    - pip install coverage

env:
    - RAS_SM_PATH=./
    - NOTIFY_VIA_LOGGING=1
    - NOTIFICATION_DEV_EMAIL=eward@ons.gov.uk
    - JWT_SECRET=abcd
    - SECURITY_USER_NAME=dummy_user
    - SECURITY_USER_PASSWORD=dummy_password

script:
    - coverage run run_tests.py

after_success:
    - codecov

branches:
    only:
        - master
