language: python
sudo: required
dist: trusty
python: '3.4'

# before_install:

cache:
    - pip
install:
    - pip install -r requirements.txt
    - pip install -r test_requirements.txt
    - pip install codecov
    - pip install coverage

script:
    - coverage run tests/test_app.py
    - coverage run tests/test_authenticator.py
    - coverage run tests/test_logging.py
    - coverage run tests/test_message.py
    - coverage run tests/test_retriever.py

after_success:
    - codecov

branches:
    only:
        - master
