language: python
sudo: required
dist: trusty
python: '3.5'

# before_install:

cache:
    - pip

install:
    - pip install pipenv
    - pipenv install --dev

script:
    - coverage run run_tests.py

services:
    - postgresql

after_success:
    - codecov

branches:
    only:
        - master

addons:
  postgresql: "9.6"
