version: '2'

services:
  db:
    image: postgres:9.4
    environment:
      POSTGRES_PASSWORD: rasmessage
      POSTGRES_USER: rasmessage
      POSTGRES_DB: messages
    ports:
      - "5433:5432"
    networks:
      - secure 

  secure-messaging-api:
    build: ./
    environment:
      SECURE_MESSAGING_DATABASE_URL: postgres://rasmessage:rasmessage@db:5432/messages
    restart: always
    depends_on:
      - db
    networks:
      - secure 
    ports:
      - "5050:5050"

networks:
  secure:
    driver: bridge
