version: '2'

services:
  db:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: securemessage
    ports:
      - "5432:5432"
    networks:
      - secure

networks:
  secure:
    driver: bridge
