swagger: '2.0'
info:
  title: Secure Message API
  version: 1.0.0
  description: This is the RAS Secure Message API
  contact:
    name: Richard Weeks
    email: richard.weeks@ons.gov.uk
    url: https://github.com/ONSdigital/ras-secure-message
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

securityDefinitions:
  accessCode:
    type: oauth2
    # This should be updated to the Token URL of your OAuth provider.
    tokenUrl: http://uaa.ons.gov.uk/oauth/token
    # This should be updated to the Authorization URL of your OAuth provider.
    authorizationUrl: http://uaa.ons.gov.uk/oauth/auth
    flow: accessCode
    scopes:
      write: allows modifying resources
      read: allows reading resources

security:
  - accessCode:
    - read

tags:
- name: Respondents
  description: Respond to surveys on behalf of a Reporting Unit
- name: Respondent Liason
  description: ONS staff supporting surveys

schemes:
- https

paths:
  /messages:
    get:
      tags:
      - Respondents
      - Respondent Liason
      summary: Fetches a list of users secure messages
      operationId: getMessages
      description: returns list of secure messages
      produces:
      - application/vnd.collection+json
      parameters:
      - in: query
        name: limit
        description: Limit number of messages returned
        required: false
        type: integer
        format: int32
      - in: query
        name: page
        description: Messages page number
        type: integer
        format: int32
      - in: query
        name: reportingUnit
        description: Reporting Unit
        required: false
        type: string
      - in: query
        name: survey
        description: Survey name
        required: false
        type: string
      - in: query
        name: case
        description: Case ID
        required: false
        type: integer
        format: int64
        minimum: 0
        maximum: 50
      responses:
        200:
          description: Message results matching criteria
          schema:
            type: array
            items:
              $ref: '#/definitions/Message'
          examples:
            application/vnd.collection+json:
              messages:
                message1:
                  id: 1
                  threadId: 1
                  msg_to: richard.weeks@ons.gov.uk
                  msg_from: respondent@abcdef.com
                  subject: Survey enquiry
                  body: 'Message 1'
                  _links:
                    self:
                      href: https://virtserver.swaggerhub.com/rjweeks/securemessage/1.0.0/message/1
                message2:
                  id: 2
                  threadId: 2
                  msg_to: richard.weeks@ons.gov.uk
                  msg_from: respondent@xyz.com
                  subject: Survey results
                  body: 'Message 2'
                  _links:
                    self:
                      href: https://virtserver.swaggerhub.com/rjweeks/securemessage/1.0.0/message/2
              _links:
                self:
                  href: https://virtserver.swaggerhub.com/rjweeks/securemessage/1.0.0/messages?page=3&limit=10
                first:
                  href: https://virtserver.swaggerhub.com/rjweeks/securemessage/1.0.0/messages
                next:
                  href: https://virtserver.swaggerhub.com/rjweeks/securemessage/1.0.0/messages?page=4&limit=10
                prev:
                  href: https://virtserver.swaggerhub.com/rjweeks/securemessage/1.0.0/messages?page=2&limit=10
        400:
          description: Bad syntax
        403:
          description: Forbidden

  /message/send:
    post:
      tags:
      - Respondents
      - Respondent Liason
      summary: Sends a secure message
      operationId: sendMessage
      description: Sends a secure message
      consumes:
      - application/vnd.collection+json
      produces:
      - application/vnd.collection+json
      parameters:
      - in: body
        name: Message
        description: Message to send
        schema:
          $ref: '#/definitions/Message'
      responses:
        201:
          description: Message sent
          examples:
            application/vnd.collection+json:
              result: Message sent
        400:
          description: Bad syntax
        405:
          description: Method not allowed

  /message/{id}:
    get:
      parameters:
      - name: id
        in: path
        description: Message ID
        required: true
        type: integer
        format: int64
      - in: query
        name: reportingUnit
        description: Reporting Unit
        required: false
        type: string
      - in: query
        name: survey
        description: Survey name
        required: false
        type: string
      tags:
      - Respondents
      - Respondent Liason
      summary: Fetch message by id
      operationId: getMessage
      description: Fetch message by id
      produces:
      - application/vnd.collection+json
      responses:
        200:
          description: Returns message by id
          schema:
            type: array
            items:
              $ref: '#/definitions/Message'
          examples:
            application/vnd.collection+json:
              msg_to: richard.weeks@ons.gov.uk
              msg_from: respondent@xyz.com
              body: 'Return message details by ID'
        400:
          description: Bad syntax
        403:
          description: Forbidden
        404:
          description: Message not found
    put:
      parameters:
      - name: id
        in: path
        description: Message ID
        required: true
        type: integer
        format: int64
      - name: read
        in: query
        description: Mark message read or unread
        required: false
        type: boolean
      tags:
      - Respondents
      - Respondent Liason
      summary: Update message status by id
      operationId: updateMessage
      description: Update message status by id
      produces:
      - application/vnd.collection+json
      responses:
        200:
          description: Updated message by id
        403:
          description: Forbidden
        404:
          description: Message not found

  /threads:
    get:
      parameters:
      - in: query
        name: ru
        description: Reporting Unit
        required: true
        type: string
      - in: query
        name: survey
        description: Survey name
        required: false
        type: string
      tags:
      - Respondents
      - Respondent Liason
      summary:
        Return a list of threads for an RU and Survey
      operationId: getThreadsForRU
      description: Return a list of Threads IDs for an RU
      responses:
        200:
          description: Thread IDs
          schema:
            type: array
            items:
              type: integer
              format: int64
              example: 98284e51-2e9d-4849-8e3b-ebb4bd48cc18

  /thread/{id}:
    get:
      parameters:
      - in: path
        name: id
        description: Thread ID
        required: true
        type: integer
        format: int64
      tags:
      - Respondents
      - Respondent Liason
      summary: Returns a thread
      operationId: getThread
      description: Returns a thread
      produces:
      - application/vnd.collection+json
      responses:
        200:
          description: Thread
          schema:
            type: array
            items:
              $ref: '#/definitions/Thread'
        400:
          description: Bad syntax
        403:
          description: Forbidden

  /archives:
    get:
      parameters:
      - in: query
        name: survey
        description: Survey name
        required: false
        type: string
      tags:
      - Respondents
      - Respondent Liason
      summary: Returns a list of archives
      operationId: getArchives
      description: Returns a list of archives
      produces:
      - application/vnd.collection+json
      responses:
        200:
          description: Archives
          schema:
            type: array
            items:
              $ref: '#/definitions/Archive'
        400:
          description: Bad syntax
        403:
          description: Forbidden

  /archive/{id}:
    get:
      parameters:
      - in: path
        name: id
        description: Archive ID
        required: true
        type: string
      tags:
      - Respondents
      - Respondent Liason
      summary: Return details of an archive
      operationId: getArchive
      description: Returns details of a secure message archive
      produces:
      - application/vnd.collection+json
      responses:
        200:
          description: Message ID's in this archive
          schema:
            type: array
            items:
              type: integer
              format: int64
              example: 98284e51-2e9d-4849-8e3b-ebb4bd48cc18

definitions:
  Message:
    type: object
    required:
    - msg_to
    - msg_from
    - body
    properties:
      msgId:
        type: string
        description: Message identifier (UUID)
        example: f9419ea4-029e-40cd-bd9c-115533dae8c5
      threadId:
        type: string
        description: Thread identifier (UUID)
        example: 212faf46-931f-4170-9b96-949e20722126
      msg_to:
        type: object
        required:
        - id
        properties:
          id:
            type: string
            format: urn
            example: urn:ons.gov.uk:id:respondent:001.234.56789
          emailAddress:
            type: string
            format: email
            example: "richard.weeks@ons.gov.uk"
          firstName:
            type: string
            example: "Richard"
          lastName:
            type: string
            example: "Weeks"
      msg_from:
        type: string
        description: Message sender
        example: Andrew Torrance
      subject:
        type: string
        example: Survey enquiry
      body:
        type: string
        format: byte

  Thread:
    type: object
    required:
    - id
    - messages
    properties:
      id:
        type: string
        example: 73685db6-9c76-44ea-a4e9-2cfb1f1eacf8
      messages:
        type: array
        items:
          $ref: '#/definitions/Message'

  Archive:
    type: object
    required:
    - id
    - messages
    properties:
      id:
        type: string
        example: 4d5818b3-ecfa-41b3-bf31-4cbe396d327b
      messages:
        type: array
        items:
          $ref: '#/definitions/Message'

# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /rjweeks/securemessage/1.0.0
