"""new 

Revision ID: 4dbabe4dfe9b
Revises: feeffdf73cd1
Create Date: 2021-07-22 16:56:35.299719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dbabe4dfe9b'
down_revision = 'feeffdf73cd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
