"""new1 

Revision ID: b7e91b1bfb94
Revises: 4dbabe4dfe9b
Create Date: 2021-07-22 17:15:06.799859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7e91b1bfb94'
down_revision = '4dbabe4dfe9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('test2', sa.Boolean(), nullable=True), schema='securemessage')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation', 'test2', schema='securemessage')
    # ### end Alembic commands ###
