apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secure-message
  namespace: {{ .Values.namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  refreshInterval: 1m
  data:
  - secretKey: client-id
    remoteRef:
      key: secure-message
      property: client-id
      version: latest
  - secretKey: client-secret
    remoteRef:
      key: secure-message
      property: client-secret
      version: latest