apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
spec:
  backendType: gcpSecretsManager
  projectId: {{ .Values.gcp.project }}
  data:
    - key: {{ .Chart.Name }}
      name: {{ .Chart.Name }}
      version: latest
      property: client-id
    - key: {{ .Chart.Name }}
      name: {{ .Chart.Name }}
      version: latest
      property: client-secret
