apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  client-id: {{ .Values.client.id |  b64enc | quote  }}
  client-secret: {{ .Values.client.secret |  b64enc | quote  }}

