env: minikube
namespace: minikube

replicas: 1
rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1

image:
  name: eu.gcr.io/ons-rasrmbs-management
  pullPolicy: IfNotPresent

database:
  managedPostgres: false
  secrets:
    usernameKey: username
    passwordKey: password
    nameKey: db-name

container:
  port: 8080
service:
  port: 80

resources:
  requests:
    memory: "128Mi"

client:
  id: secure_message
  secret: password
